name: build

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v4
        with:
          push: true
          file: Dockerfile.prod
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/diplom_12:latest
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Copy on server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          password: ${{ secrets.SSH_PASSWORD }}
          username: ${{ secrets.SSH_USER }}
          source: "deploy/*"
          target: "todolist_project"
          strip_components: 1
      - name: Run app
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          password: ${{ secrets.SSH_PASSWORD }}
          username: ${{ secrets.SSH_USER }}
          script: |
            cd todolist_project
            docker-compose pull
            docker-compose up -d
      - name: Cleanup
        if: always()
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          password: ${{ secrets.SSH_PASSWORD }}
          username: ${{ secrets.SSH_USER }}
          script: |
            docker system prune -a -f
